ENT-4071: Added Braze Client
openedx-unsupported/ecommerce-worker pull request #115
Opened 2021-02-05 14:24 UTC by irfanuddinahmad

**Merge checklist:**
- [ ] Any new requirements are in the right place (do **not** manually modify the `requirements/*.txt` files)
    - `base.in` if needed in production
    - `test.in` for test requirements
    - `make upgrade && make requirements` have been run to regenerate requirements
- [ ] [Version](https://github.com/edx/ecommerce-worker/blob/master/setup.py) bumped

**Post merge:**
- [ ] Tag pushed and a new [version](https://github.com/edx/ecommerce-worker/releases) released
    - *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- [ ] After versioned build finishes in [Travis](https://travis-ci.org/github/edx/ecommerce-worker), verify version has been pushed to [PyPI](https://pypi.org/project/edx-ecommerce-worker/)
    - Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
    (so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- [ ] PR created in [ecommerce](https://github.com/edx/ecommerce) to upgrade dependencies (including ecommerce-worker)
    - This **must** be done after the version is visible in PyPi as `make upgrade` in ecommerce will look for the latest version in PyPi.
    - Note: the ecommerce-worker constraint in ecommerce **must** also be bumped to the latest version in PyPi.
- [ ] Deploy `ecommerce`
- [ ] Deploy `ecomworker` on GoCD.
    - While some functions in ecommerce-worker are run via ecommerce, others are handled by a standalone AMI and must be
      released via GoCD.

2021-02-09 06:02 UTC, sameenfatima78 approved these changes
LGTM, just some minor suggestions

2021-02-09 06:02 UTC, sameenfatima78 commented on ecommerce_worker/braze/v1/client.py
> +    def __create_request(self, body):
Would be nice if we can add a description of this method in the docstring

2021-02-09 06:02 UTC, sameenfatima78 commented on ecommerce_worker/braze/v1/client.py
> +        """
Would be nice if we can add a description of this method in the docstring

2021-02-09 06:02 UTC, sameenfatima78 commented on ecommerce_worker/braze/v1/exceptions.py
> +    pass
New line is missing

2021-02-09 11:53 UTC, saleem-latif commented on ecommerce_worker/braze/v1/client.py
> +        """
Please update the docstrings according to the guideline @ 
https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html

2021-02-09 11:53 UTC, saleem-latif commented on ecommerce_worker/configuration/base.py
> +BRAZE = {
Please add toggle details like, 
```
    # .. toggle_name: BRAZE['BRAZE_ENABLE']
    # .. toggle_implementation: PythonConstant
    # .. toggle_default: False
    # .. toggle_description: Toggle for allowing emails to be sent via Braze instead of sailthru
    # .. toggle_use_cases: open_edx
    # .. toggle_creation_date: 2021-02-09
    # .. toggle_target_removal_date: None
    # .. toggle_warnings: None
    # .. toggle_tickets: ENT-4071
```

2021-02-09 12:13 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/client.py
> +    def __create_request(self, body):
Done

2021-02-09 12:13 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/client.py
> +        """
Done

2021-02-09 12:14 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/client.py
> +        """
Done

2021-02-09 12:20 UTC, irfanuddinahmad commented on ecommerce_worker/configuration/base.py
> +BRAZE = {
Done

2021-02-10 08:04 UTC, saleem-latif requested changes

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/client.py
> +""" Braze Client functions. """
Please format this as multi-line.

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/client.py
> +    Returns the Braze configuration for the specified site.
Add information about the site_code argument.

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/client.py
> +    Returns:
add an empty lune above Returns and Raises.

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/client.py
> +        Content-Type: application/json
incorrect indention for 
```
Content-Type: application/json 
...
```

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/client.py
> +        {
please fix indentation here

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/client.py
> +        email = dict()
I think it would be more readable to initialize it via string literals?
```
email = {
    'app_id': self.webapp_api_key,
    'subject': subject,
    'from': DEFAULT_FROM_EMAIL,
    'body': {
        'external_user_ids': email_ids,
        messages: {
            'email': email
        }
    }
}
```

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/exceptions.py
> +""" Braze-related exception classes. """
please format it as multi-line

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/exceptions.py
> +    pass
No need for the pass statement.

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/exceptions.py
> +        :param float reset_epoch_s: Unix timestamp for when the API may be called again.
Please change this to

```
A rate limit error was encountered.

Arguments:
    reset_epoch_s (float): Unix timestamp for when the API may be called again.
```

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/exceptions.py
> +    pass
no need for the pass statement

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/tests/test_client.py
> +""" Test for Braze client. """
Please use multi-line dosctring

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/tests/test_client.py
> +            status=status_code)
move the closing bracket to the new line.

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/tests/test_client.py
> +            'message': "Not a Success",
nit: use single quotes.

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/client.py
> +DEFAULT_REST_API_URL = "https://rest.iad-06.braze.com"  # sdk.iad-06.braze.com
I think these should be moved to the configuration files.

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/client.py
> +        self.rest_api_key = rest_api_key
Please add a docstring for `__init__`

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/client.py
> +        if message != 'success':
condition for success scenario is different here as compared to Line: 93, is it intentional?

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/client.py
> +        Returns:
nit: please add an empty line above Returns

2021-02-10 08:04 UTC, saleem-latif commented on ecommerce_worker/braze/v1/client.py
> +            {'Authorization': u'Bearer {}'.format(self.rest_api_key), 'Content-Type': 'application/json'}
We do not need auth token for the braze? Does API Key act as the auth token?

2021-02-10 08:47 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/client.py
> +            {'Authorization': u'Bearer {}'.format(self.rest_api_key), 'Content-Type': 'application/json'}
Yes

2021-02-10 09:47 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/client.py
> +""" Braze Client functions. """
Done

2021-02-10 09:48 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/client.py
> +    Returns the Braze configuration for the specified site.
Done

2021-02-10 09:48 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/client.py
> +    Returns:
Done

2021-02-10 09:48 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/client.py
> +        Content-Type: application/json
Done

2021-02-10 09:48 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/client.py
> +        {
Done

2021-02-10 09:48 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/client.py
> +DEFAULT_REST_API_URL = "https://rest.iad-06.braze.com"  # sdk.iad-06.braze.com
Done

2021-02-10 09:49 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/client.py
> +        self.rest_api_key = rest_api_key
Done

2021-02-10 09:50 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/client.py
> +        Returns:
Done

2021-02-10 10:03 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/client.py
> +        if message != 'success':
Good catch! ... Done

2021-02-10 10:32 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/client.py
> +        email = dict()
Done

2021-02-10 10:33 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/exceptions.py
> +""" Braze-related exception classes. """
Done

2021-02-10 10:33 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/exceptions.py
> +    pass
Done

2021-02-10 10:34 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/exceptions.py
> +        :param float reset_epoch_s: Unix timestamp for when the API may be called again.
Done

2021-02-10 10:34 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/exceptions.py
> +    pass
Done

2021-02-10 10:34 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/tests/test_client.py
> +""" Test for Braze client. """
Done

2021-02-10 10:34 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/tests/test_client.py
> +            status=status_code)
Done

2021-02-10 10:34 UTC, irfanuddinahmad commented on ecommerce_worker/braze/v1/tests/test_client.py
> +            'message': "Not a Success",
Done

2021-02-10 11:00 UTC, saleem-latif approved these changes

2021-02-10 11:07 UTC, merged