refactor: Remove EdxRestApiClient usage in ecommerce-worker
openedx-unsupported/ecommerce-worker pull request #163
Opened 2022-04-08 17:01 UTC by ruzniaievdm

# ⛔️ DEPRECATION WARNING

**This repository is deprecated and in maintainence-only operation while we work on a replacement, please see [this announcement](https://discuss.openedx.org/t/deprecation-removal-ecommerce-service-depr-22/6839) for more information.**

Although we have stopped integrating new contributions, we always appreciate security disclosures and patches sent to [security@edx.org](mailto:security@edx.org)

## Anyone internally merging to this repository is expected to [release and monitor their changes](https://openedx.atlassian.net/wiki/spaces/RS/pages/1835106870/How+to+contribute+to+our+repositories); if you are not able to do this DO NOT MERGE, please coordinate with someone who can to ensure that the changes are released.

**Merge checklist:**
- [ ] Any new requirements are in the right place (do **not** manually modify the `requirements/*.txt` files)
    - `base.in` if needed in production
    - `test.in` for test requirements
    - `make upgrade && make requirements` have been run to regenerate requirements
- [ ] [Version](https://github.com/edx/ecommerce-worker/blob/master/setup.py) bumped

**Post merge:**
- [ ] Tag pushed and a new [version](https://github.com/edx/ecommerce-worker/releases) released
    - *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- [ ] After versioned build finishes in [GitHub CI](https://github.com/edx/ecommerce-worker/actions?query=workflow%3A%22Python+CI%22), verify version has been pushed to [PyPI](https://pypi.org/project/edx-ecommerce-worker/)
    - Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
    (so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- [ ] PR created in [ecommerce](https://github.com/edx/ecommerce) to upgrade dependencies (including ecommerce-worker)
    - This **must** be done after the version is visible in PyPi as `make upgrade` in ecommerce will look for the latest version in PyPi.
    - Note: the ecommerce-worker constraint in ecommerce **must** also be bumped to the latest version in PyPi.
- [ ] Deploy `ecommerce`
- [ ] Deploy `ecomworker` on GoCD.
    - While some functions in ecommerce-worker are run via ecommerce, others are handled by a standalone AMI and must be
      released via GoCD.

2022-04-08 17:01 UTC, openedx-webhooks commented
Thanks for the pull request, @ruzniaievdm! I've created [OSPR-6600](https://openedx.atlassian.net/browse/OSPR-6600) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-04-11 15:24 UTC, dianakhuang reviewed
Overall, it looks good, but I think this may fail quality checks due to the imports not being sorted due to our conventions.

2022-04-11 15:24 UTC, dianakhuang commented on ecommerce_worker/fulfillment/v1/tests/test_tasks.py
> +from requests import HTTPError
I think these imports might need to be `isort`ed.

2022-04-11 15:24 UTC, dianakhuang commented on ecommerce_worker/utils.py
> +from requests import HTTPError
Same with these imports.

2022-04-11 15:42 UTC, natabene commented
@ruzniaievdm Thank you for the contribution! Once you have signed the Contributor Agreement and it has been processed, you will receive a confirmation via email from our Legal team. We then will be able to review this and all your future code contributions.

2022-04-12 09:45 UTC, idegtiarov commented
Hi @natabene, Dmytro is covered by the RacconGang company CLA. I added him to the [RG contributors list ](https://docs.google.com/spreadsheets/d/14R9csby27Wru31FXQiXPCv_0lgvnHe1HW1nyaqZbXu0/edit#gid=0).

Does there anything I can help with to proceed with the PR?

2022-04-12 13:41 UTC, natabene commented
@idegtiarov Thanks for looking into this, the check should clear soon, probably by tomorrow.

2022-04-12 14:54 UTC, idegtiarov commented
@natabene Thank you!

2022-04-18 09:33 UTC, ruzniaievdm commented on ecommerce_worker/fulfillment/v1/tests/test_tasks.py
> +from requests import HTTPError
done

2022-04-18 09:33 UTC, ruzniaievdm commented
@dianakhuang Hi, I sorted the imports with `isorted`

2022-04-18 14:10 UTC, dianakhuang approved these changes
Looks good to me! I still want to wait for the owning team's review before I merge, though.

2022-06-02 15:09 UTC, feanil requested changes
A couple of small changes and one missing test and then I think this is good to go.

2022-06-02 15:09 UTC, feanil commented on ecommerce_worker/configuration/local.py
> +BACKEND_SERVICE_EDX_OAUTH2_PROVIDER_URL = 'http://localhost:18000/oauth2/'
Since this value is not changing from base.py, I think it's safe to also remove this override.

2022-06-02 15:09 UTC, feanil commented on ecommerce_worker/configuration/test.py
> +BACKEND_SERVICE_EDX_OAUTH2_PROVIDER_URL = 'http://localhost:18000/oauth2/'
Same here, since this builds on top of base and the value is the same, we don't need to re-state it here.

2022-06-02 15:09 UTC, feanil commented on ecommerce_worker/utils.py
> +        raise requests.RequestException(response=response) from exc
Looks like this line is no longer being covered in testing, we should test that we handle this exception properly by adding a test for it.

2022-06-14 15:08 UTC, ruzniaievdm commented
@feanil I've added to my PR test for increase coverage and also removed variable from envs
The test can be found at the path: `ecommerce_worker/tests/test_utils.py`

2022-06-14 19:58 UTC, feanil submitted a review, later dismissed

2022-06-14 19:58 UTC, feanil commented on ecommerce_worker/configuration/base.py
> +BACKEND_SERVICE_EDX_OAUTH2_PROVIDER_URL = 'http://localhost:18000/oauth2/'
@dianakhuang have these 3 settings been created and deployed for the ecommerce worker?

We should also add these to [the olive release page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3396501578/Olive), and make note of the removal of the `JWT_SECRET_KEY` and `JWT_ISSUER`

2022-06-14 19:58 UTC, feanil commented on ecommerce_worker/email/v1/utils.py
> +            data={
Separating the creation of the `post_data` from the actual call can make debugging easier in the future.  Please put use the `post_data` variable to build the post_data and then use it in the call.

2022-06-14 19:58 UTC, feanil commented on ecommerce_worker/email/v1/utils.py
> +        data = response.json()
You're not handling when the data that comes back is not JSON.  Should that JSONError get expressad as an HTTPError to maintain the current behavior or is it safe to raise a JSON error here?

2022-06-14 19:58 UTC, feanil commented on ecommerce_worker/fulfillment/v1/tasks.py
> +            params={
Same as with the POST data above, pull the params out into a variable to ease future introspection and debugging.

2022-06-14 19:58 UTC, feanil commented on ecommerce_worker/fulfillment/v1/tasks.py
> +            'Fulfillment of order [%s] failed because of HTTPError. Retrying',
@dianakhuang are there any splunk alerts on these log messages that might need to be updated?

2022-06-14 19:58 UTC, feanil commented on ecommerce_worker/fulfillment/v1/tests/test_tasks.py
> +        self.mock_access_token_api()
since nearly all tests in this class need this setup, does it make more sense to do it in the `setUp` function instead or as a [pytest autouse fixture](https://docs.pytest.org/en/6.2.x/fixture.html#autouse-fixtures-fixtures-you-don-t-have-to-request)

2022-06-14 19:58 UTC, feanil commented on ecommerce_worker/utils.py
> +            data={
Pull the data dict out into a variable for easier future debugging.

2022-06-14 19:59 UTC, feanil commented
@ruzniaievdm sorry, I noticed a few more things on my second round of review than I expected.

2022-06-15 14:52 UTC, ruzniaievdm commented on ecommerce_worker/email/v1/utils.py
> +        data = response.json()
I'm not sure I understood correctly
`response.json()` raises exception in the following scenario - response doesn’t contain any data or contains invalid JSON. In this case, I can additionally check the status `response.status_code == 204` before `response.json()`

But I don't think we need to add JSONError handler, because response always be contains a dict with updated key pair -  
```
update_status = {
    'offer_assignment_id': offer_assignment_id,
    'send_id': send_id
}
```

2022-06-15 14:53 UTC, ruzniaievdm commented on ecommerce_worker/email/v1/utils.py
> +            data={
done

2022-06-15 14:53 UTC, ruzniaievdm commented on ecommerce_worker/fulfillment/v1/tasks.py
> +            params={
done

2022-06-15 14:54 UTC, ruzniaievdm commented on ecommerce_worker/fulfillment/v1/tests/test_tasks.py
> +        self.mock_access_token_api()
done

2022-06-15 14:54 UTC, ruzniaievdm commented on ecommerce_worker/utils.py
> +            data={
done

2022-06-15 15:52 UTC, ruzniaievdm commented
@feanil I've updated my PR, but left unchanged discussion about JSONError, if there is a need - I will update

2022-06-22 12:13 UTC, feanil commented on ecommerce_worker/email/v1/utils.py
> +        data = response.json()
@ruzniaievdm right, but if there is a misconfiguration in the upstream service or at the nginx layer, you might get a non-JSON response.  In this case, we should treat this as a failed request  and not propogate the JSONError exception outside of this function.

2022-06-22 12:13 UTC, feanil commented on ecommerce_worker/fulfillment/v1/tasks.py
> +            'Fulfillment of order [%s] failed because of HTTPError. Retrying',
@dianakhuang checking back in on this since I can't verify if this will break any existing splunk alerts.

2022-06-22 12:13 UTC, feanil commented on ecommerce_worker/utils.py
> +            'client_id': get_configuration('BACKEND_SERVICE_EDX_OAUTH2_KEY'),
@dianakhuang have these two settings been added to the staging and production settings for the ecommerce worker for edx.org?

2022-06-22 12:13 UTC, feanil commented on ecommerce_worker/fulfillment/v1/tests/test_tasks.py
> +        self.mock_access_token_api()
@ruzniaievdm did this change not get pushed up?  I don't see this moved to a setup call or added as a fixture.

2022-06-22 12:13 UTC, feanil commented on ecommerce_worker/utils.py
> +        )
```suggestion
        post_data = {
            'grant_type': 'client_credentials',
            'client_id': get_configuration('BACKEND_SERVICE_EDX_OAUTH2_KEY'),
            'client_secret': get_configuration('BACKEND_SERVICE_EDX_OAUTH2_SECRET'),
            'token_type': 'jwt',
        }
        headers = {
            'User-Agent': 'ecommerce-worker',
        }
        response = requests.post(
            oauth_access_token_url,
            data=post_data,
            headers=post_data,
            timeout=(REQUEST_CONNECT_TIMEOUT, REQUEST_READ_TIMEOUT)
        )
```

@ruzniaievdm I mean like this, so that we can see the values of the data and headers before we prep the call while debugging.

2022-06-23 10:18 UTC, ruzniaievdm commented on ecommerce_worker/utils.py
> +        )
done. Determined `headers` variable additionally. А third commit will be added

2022-06-23 10:23 UTC, ruzniaievdm commented on ecommerce_worker/fulfillment/v1/tests/test_tasks.py
> +        self.mock_access_token_api()
hm, this requested changes exists in second [commit](https://github.com/openedx/ecommerce-worker/pull/163/commits/7c2cfaf718178edd273d5a6dd7c376e53280a7bc), if you mean adding `mock_access_token_api` to `setUp` to

2022-06-23 11:49 UTC, ruzniaievdm commented on ecommerce_worker/email/v1/utils.py
> +        data = response.json()
added `JSONDecodeError` to catching errors

2022-06-23 11:51 UTC, ruzniaievdm commented
@feanil added requested changes to third [commit](https://github.com/openedx/ecommerce-worker/pull/163/commits/ab2b2b336cdc2c8afaa6b5e63b5889bf367f0716)
If you will approve this changes please give a chance to make a rebase to one commit.

2022-06-23 15:14 UTC, feanil commented on ecommerce_worker/fulfillment/v1/tests/test_tasks.py
> +        self.mock_access_token_api()
Ah, missed that in my review, sorry, must have been looking at an old version. :+1:

2022-06-23 15:19 UTC, feanil commented
This generally looks good to me to merge, @ruzniaievdm can you add a note about the settings being added/removed to the Olive release page?

@dianakhuang I want to make sure those settings are already set for edx.org before we merge so we don't break eCommerce worker.

2022-06-23 16:18 UTC, dianakhuang commented
Looking at the settings, but there seems to be a bunch of errors in tests we need to look at, too.

2022-06-23 18:21 UTC, dianakhuang commented
Settings are not there, and they may take a bit for me to update since I need to figure out what those values should be. 

Doesn't seem to be any fulfillment Splunk alerts that look for that specific part of the error message, so I think we should be safe with that change.

2022-06-29 15:39 UTC, dianakhuang commented
Settings have been added for edx.org. I need to update a few other places in prep for next release, etc, but this should be good to merge when we're ready.

2022-06-29 20:15 UTC, merged

2022-06-29 20:15 UTC, openedx-webhooks commented
@ruzniaievdm 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/ecommerce-worker&entry.867055334=https://github.com/openedx/ecommerce-worker/pull/163&entry.1484655318=https://github.com/ruzniaievdm&entry.752974735=2022-04-08+17:01&entry.1917517419=2022-06-29+20:15&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->