Pass sku value in SailThru purchase call.
openedx-unsupported/ecommerce-worker pull request #29
Opened 2017-06-08 12:41 UTC by adeelkhan

LEARNER-1193

WIP - Passing sku value to Sailthru purchase call.

2017-06-08 12:45 UTC, ahsan-ul-haq commented on ecommerce_worker/sailthru/v1/tasks.py
> +    if course_data.get('sku', None):
No need to put None it will be by default

2017-06-08 12:45 UTC, ahsan-ul-haq commented on ecommerce_worker/sailthru/v1/tasks.py
> +def _get_verified_course_sku(api_response):
Add docstring

2017-06-08 12:49 UTC, clintonb approved these changes

2017-06-08 12:49 UTC, clintonb commented on ecommerce_worker/sailthru/v1/tasks.py
> +    if course_data.get('sku', None):
Why is the if statement even necessary? Can the API accept `None` here?

2017-06-08 12:49 UTC, clintonb commented on ecommerce_worker/sailthru/v1/tasks.py
> +                    sku = product['stockrecords'][0]['partner_sku']
You want to return the SKU with USD currency. Don't assume that is the first one.

2017-06-08 17:15 UTC, schenedx requested changes
We should get the SKU from ecommerce IDA when the function here is called.
Then put the SKU into a new `var` key, together with the SKUs we get from content library

2017-06-09 17:57 UTC, schenedx requested changes
Please also update the unit test accordingly

2017-06-09 17:57 UTC, schenedx commented on ecommerce_worker/sailthru/v1/tasks.py
> +    if course_data.get('sku'):
You should no longer get the `purchase_sku` from course data. Instead, the purchase_sku should be the value passed in from the ecommerce service.

2017-06-09 17:57 UTC, schenedx commented on ecommerce_worker/sailthru/v1/tasks.py
> +        item['vars']['sku'] = course_data['sku']
You should assign the `purchase_sku` into a new var in `item` dictionary. For example:
`item['vars']['purchase_sku'] = purchase_sku`

2017-06-09 17:57 UTC, schenedx commented on ecommerce_worker/sailthru/v1/tasks.py
> +def _get_course_content(course_id, course_url, sailthru_client, site_code, config, sku=None):
Don't need to pass the sku from ecommerce into this function.

2017-06-09 17:57 UTC, schenedx commented on ecommerce_worker/sailthru/v1/tasks.py
> +            response = _get_course_content_from_ecommerce(course_id, site_code=site_code, sku=sku)
Don't need to pass `sku` into `_get_course_content_from_ecommerce`

2017-06-09 17:57 UTC, schenedx commented on ecommerce_worker/sailthru/v1/tasks.py
> +def _get_course_content_from_ecommerce(course_id, site_code=None, sku=None):
You don't need the `sku` passed into this function

2017-06-09 17:57 UTC, schenedx commented on ecommerce_worker/sailthru/v1/tasks.py
> +        'sku': sku
`sku` is not needed to return

2017-06-09 17:57 UTC, schenedx commented on ecommerce_worker/sailthru/v1/tasks.py
> +    course_data = _get_course_content(course_id, course_url, sailthru_client, site_code, config, sku)
No need to pass the `sku` into the function, and then pass it back into `course_data`

2017-06-12 12:26 UTC, adeelkhan commented
@clintonb @schenedx Made requested changes please review.

2017-06-12 12:27 UTC, clintonb approved these changes

2017-06-12 14:06 UTC, schenedx approved these changes
👍

2017-06-13 08:50 UTC, merged