Add email opt in to ecom worker
openedx-unsupported/ecommerce-worker pull request #33
Opened 2018-10-23 22:17 UTC by Dillon-Dumesnil

2018-10-23 22:18 UTC, Dillon-Dumesnil commented on ecommerce_worker/fulfillment/v1/tasks.py
> +def fulfill_order(self, order_number, site_code=None, email_opt_in=False):
Should this even be a bool or should we just make it a string since it will just get passed to the put request?

2018-10-23 22:19 UTC, Dillon-Dumesnil commented on ecommerce_worker/fulfillment/v1/tests/test_tasks.py
> +        self.API_URL = self.API_URL + '?email_opt_in=' + email_opt_in_str
Turns out this line isn't actually necessary (tests pass regardless), but I think it explains more about what we are expecting in the test for the path so I think it is better to leave it in.

2018-10-23 22:21 UTC, Dillon-Dumesnil commented on ecommerce_worker/fulfillment/v1/tests/test_tasks.py
> +        email_opt_in_API_URL = self.API_URL + '?email_opt_in=' + email_opt_in_str
Turns out this line isn't actually necessary (tests pass regardless), but I think it explains more about what we are expecting in the test for the path so I think it is better to leave it in.

2018-10-23 22:23 UTC, Dillon-Dumesnil commented on ecommerce_worker/fulfillment/v1/tests/test_tasks.py
> +        email_opt_in_api_url = self.API_URL + '?email_opt_in=' + email_opt_in_str
Turns out this line isn't actually necessary (tests pass regardless), but I think it explains more about what we are expecting in the test for the path so I think it is better to leave it in.

2018-10-24 01:38 UTC, jmyatt commented on ecommerce_worker/configuration/test.py
> +ECOMMERCE_API_ROOT = 'http://localhost:18130/api/v2/'
I think it makes sense to change this on local but not here in test, since in a test context we won't be hitting our local devstack instance of ecommerce

2018-10-24 01:40 UTC, jmyatt commented on ecommerce_worker/fulfillment/v1/tasks.py
> +def fulfill_order(self, order_number, site_code=None, email_opt_in=False):
I think a bool here in this function signature makes the most sense, but pls ensure that we don't need to cast it to a string on line 42 below where we send it in the API.  Ideally we use a bool everywhere and the REST framework (slumber) handles casting it to a string upon send

2018-10-24 01:44 UTC, jmyatt requested changes
just a couple notes

2018-10-24 03:02 UTC, jmyatt commented on ecommerce_worker/fulfillment/v1/tasks.py
> +def fulfill_order(self, order_number, site_code=None, email_opt_in=False):
actually nvm - your test in this PR confirms that the bool gets properly expressed as a string in the API request

2018-10-24 03:05 UTC, jmyatt commented on ecommerce_worker/configuration/test.py
> +ECOMMERCE_API_ROOT = 'http://localhost:18130/api/v2/'
as discussed, let's leave this change as is since we never have an ecommerce instance running on port 8002

2018-10-24 03:10 UTC, jmyatt commented
please change the commit message to something more specific such as "Add email_opt_in arg to fulfill_order task"

2018-10-24 14:35 UTC, jmyatt approved these changes
:shipit:

2018-10-24 14:35 UTC, merged