WIP: ENT-1362 task for sending code assignment email
openedx-unsupported/ecommerce-worker pull request #36
Opened 2018-11-30 10:20 UTC by irfanuddinahmad

Description: This PR adds a task in the extensions api to send code assignment emails to learners

Jira: https://openedx.atlassian.net/browse/ENT-1362

2018-12-12 13:27 UTC, georgebabey requested changes
couple suggestions, overall looks good

2018-12-12 13:27 UTC, georgebabey commented on ecommerce_worker/sailthru/v1/tasks.py
> +def send_code_assignment_email(self, user_email, code, subject, email_body, site_code=None):
nit - I think we should update the naming to be offer_assignment as that is the model we are using to store this information. I know offer/coupon/code all get used interchangeably in various places, but I think making this match the ecomm model will make it more clear

2018-12-12 13:27 UTC, georgebabey commented on ecommerce_worker/sailthru/v1/tasks.py
> +            logger.exception(
Note to self: we should route these exceptions to our team as it means the learner got an email, but the assignment for some reason never happened.

2018-12-12 13:27 UTC, georgebabey commented on ecommerce_worker/sailthru/v1/tasks.py
> +            'An error occurred while retrieving email update status data for '
Exception makes it sound like you're just fetching data (`retrieving email update status`), but this exception occurs when trying to modify the assignment status

2018-12-12 13:27 UTC, georgebabey commented on ecommerce_worker/sailthru/v1/tasks.py
> +            'An error occurred while retrieving email update status data for '
Also can we log the exception to help us debug if this does happen, and perhaps only except on `exceptions.HttpServerError` or `exceptions.Timeout` rather than this broad except

2018-12-13 16:39 UTC, irfanuddinahmad commented on ecommerce_worker/sailthru/v1/tasks.py
> +            logger.exception(
I guess the routing would be via splunk

2018-12-13 18:41 UTC, georgebabey approved these changes

2018-12-13 18:41 UTC, merged