ENT-1362: Updated ecommerce assignment-email api call parameters
openedx-unsupported/ecommerce-worker pull request #39
Opened 2018-12-24 10:14 UTC by irfanuddinahmad

Description: This PR updates the POST parameters for the offer assignment api call in ecommerce (/api/v2/assignment-email/status)

The new request/response format is as follows:
Request
```
{
                'offer_id': 1,
                'send_id': 'XBEn85WnoQJsIhk7',
                'status': 'success',
},
```
Response
```
{
                'offer_id': 1,
                'send_id': 'XBEn85WnoQJsIhk7',
                'status': 'updated',
                'error': ''
},
```

2018-12-28 15:18 UTC, brittneyexline approved these changes

2019-01-02 09:23 UTC, muhammad-ammar requested changes
@irfanuddinahmad Loos good except one minor change.

2019-01-02 09:23 UTC, muhammad-ammar commented on ecommerce_worker/utils.py
> +def get_ecommerce_client(url_postfix='', site_code=None):
Please update the docstring for function arguments. Also add the rationale behind `url_postfix` argument?

2019-01-07 14:21 UTC, irfanuddinahmad commented on ecommerce_worker/utils.py
> +def get_ecommerce_client(url_postfix='', site_code=None):
Done

2019-01-07 15:08 UTC, merged