Define unicode in Python 3
openedx-unsupported/ecommerce-worker pull request #51
Opened 2019-01-13 16:33 UTC by cclauss

__unicode__ was removed in Python 3 because all __str__ are Unicode utf-8.

2019-01-13 16:33 UTC, edx-webhook commented
Thanks for the pull request, @cclauss! I've created [OSPR-2972](https://openedx.atlassian.net/browse/OSPR-2972) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2019-01-14 04:36 UTC, natabene commented
@cclauss  Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions.

2019-01-16 17:26 UTC, natabene commented
@cclauss  Can you let me know once all tests pass and it is ready for review?

2019-01-16 18:17 UTC, cclauss commented
The tests pass.

2019-01-17 17:17 UTC, natabene commented
@cclauss Thank you! @nedbat  Can you take a look?

2019-02-19 17:34 UTC, natabene commented
@cclauss We are good to go now, thanks for your patience. @nedbat  Please go ahead and review.

2019-02-28 18:24 UTC, nedbat requested changes

2019-02-28 18:24 UTC, nedbat commented on requirements/production.txt
> +six==1.12.0
My reading of the requirements files says this should go into base.txt.   Travis doesn't install production.txt

2019-02-28 20:12 UTC, merged

2019-02-28 20:12 UTC, edx-webhook commented
@cclauss 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/ecommerce-worker&entry.867055334=https://github.com/edx/ecommerce-worker/pull/51&entry.1484655318=https://github.com/cclauss&entry.752974735=2019-01-13+16:33&entry.1917517419=2019-02-28+20:12&entry.2133058324=Yes) so we can improve your experience in the future.